---
- hosts: alphaprime.sismonda.local
  become: yes

  tasks:
  - name: Include Nerdctl Task
    ansible.builtin.include_tasks: "../modules/docker.yml"

  - name: Crear directorio /opt/docker/syncthing
    file:
      path: /opt/docker/syncthing
      state: directory

  - name: Copiar Compose
    template:
      src: /mnt/storage/ansible/ubu2404/syncthing/opt/docker/syncthing/compose.yml
      dest: /opt/docker/syncthing/compose.yml
      owner: root
      group: root
      mode: 0640
      backup: yes

  - name: Copiar syncthing.service
    template:
      src: /mnt/storage/ansible/ubu2404/syncthing/etc/systemd/system/syncthing.service
      dest: /etc/systemd/system/syncthing.service
      owner: root
      group: root
      mode: 0644
      backup: yes
      
  - name: Configurar ejecución de syncthing.service.
    systemd:
      name: syncthing.service
      state: started
      daemon_reload: yes
      enabled: yes
