---
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    hostname: alphaprime
    volumes:
      - /mnt/storage/ollama:/root/.ollama      #llm storage
    ports:
      - 11434:11434 # Web UI
    restart: unless-stopped
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui
    container_name: open-webui
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped