# Despliega un compose.yml con un contenedor de pihole y otro de wireguard.
# Provee vpn y DNS con filtro de publicidad.
# Sincroniza un lan.list para tener dns interno.
---
- hosts: phwrgrd 
  become: yes

  tasks:
  - name: Instalar containerd, nfs-common y rysnc.
    package:
      name:
       - containerd 
       - nfs-common
       - rsync

  - name: Crear directorio /opt/utils
    file:
      path: /opt/utils
      state: directory

  - name: Crear directorio /mnt/storage
    file:
      path: /mnt/storage
      state: directory

  - name: Crear directorio /opt/containerd/phwrgrd
    file:
      path: /opt/containerd/phwrgrd/pihole/etc/dnsmasq.d
      state: directory

  - name: Crear directorio /opt/utils
    file:
      path: /opt/utils
      state: directory

  - name: Mount up device by label
    mount:
      path: /mnt/storage
      src: 10.0.0.9:/storage
      fstype: nfs
      opts: rw,soft,x-systemd.automount,rsize=131072,wsize=131072
      state: mounted

  - name: Copiar compose.yml
    template:
      src: /etc/ansible/containerd/phwrgrd/opt/containerd/phwrgrd/docker-compose.yml
      dest: /opt/containerd/phwrgrd/docker-compose.yml
      owner: root
      group: root
      mode: 0640
      backup: yes

  - name: Pi-Hole sync script
    template:
      src: /etc/ansible/containerd/phwrgrd/opt/utils/pihole-sync-slave.sh
      dest: /opt/utils/pihole-sync-slave.sh
      owner: root
      group: root
      mode: 0740
      backup: yes

  - name: Pi-Hole sync script conf
    template:
      src: /etc/ansible/containerd/phwrgrd/opt/utils/pihole-sync-slave.conf
      dest: /opt/utils/pihole-sync-slave.conf
      owner: root
      group: root
      mode: 0640
      backup: yes

  - name: Copiar phwrgrd.service
    template:
      src: /etc/ansible/containerd/phwrgrd/etc/systemd/system/phwrgrd.service
      dest: /etc/systemd/system/phwrgrd.service
      owner: root
      group: root
      mode: 0755
      backup: yes

  - name: Copiar phwrgrd-sync.service
    template:
      src: /etc/ansible/containerd/phwrgrd/etc/systemd/system/phwrgrd-sync.service
      dest: /etc/systemd/system/phwrgrd-sync.service
      owner: root
      group: root
      mode: 0755
      backup: yes

  - name: Copiar phwrgrd-sync.timer
    template:
      src: /etc/ansible/containerd/phwrgrd/etc/systemd/system/phwrgrd-sync.timer
      dest: /etc/systemd/system/phwrgrd-sync.timer
      owner: root
      group: root
      mode: 0755
      backup: yes

  - name: Unarchive nerdctl-full
    unarchive:
      src: https://github.com/containerd/nerdctl/releases/download/v1.7.6/nerdctl-full-1.7.6-linux-arm64.tar.gz 
      dest: /usr/local
      remote_src: yes

  - name: Copiar dnsmasq lan definion file
    template:
      src: /etc/ansible/containerd/phwrgrd/opt/containerd/phwrgrd/pihole/etc/dnsmasq.d/02-lan.conf
      dest: /opt/containerd/phwrgrd/pihole/etc/dnsmasq.d/02-lan.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: Reiniciar systemd-resolved.
    systemd:
      name: systemd-resolved
      state: stopped
      daemon_reload: yes
      enabled: no

  - stat:
      path: /etc/resolv.conf
    register: link

  - name: Borro /etc/resolv.conf si es un symlink
    file:
      path: /etc/resolv.conf
      state: absent
    when: link.stat.islnk is defined and link.stat.islnk

  - name: Si el /etc/resolv.conf no existe lo creo
    blockinfile:
      path: /etc/resolv.conf
      block: |
        'nameserver 127.0.0.53'
        'options edns0 trust-ad'
        'search .'
      group: root
      owner: root
      mode: 0644

  - name: Configurando /etc/resolv.conf para utilizar pihole
    lineinfile:
      path: /etc/resolv.conf
      regexp: '^nameserver 127.0.0.53'
      line: 'nameserver 8.8.8.8'

  - name: Configurar ejecución de Containerd
    systemd:
      name: containerd 
      state: started
      daemon_reload: yes
      enabled: yes

  - name: Configurar ejecución de phwrgrd.service.
    systemd:
      name: phwrgrd.service
      state: started
      daemon_reload: yes
      enabled: yes

  - name: Configurar ejecución de phwrgrd-sync.timer
    systemd:
      name: phwrgrd-sync.timer
      state: started
      daemon_reload: yes
      enabled: yes

  - name: Configurando /etc/resolv.conf para utilizar pihole
    lineinfile:
      path: /etc/resolv.conf
      regexp: '^nameserver 8.8.8.8'
      line: 'nameserver 127.0.0.1'
