---
version: "3.1"
services:
  ubuntu-16.04-samba:
    image: fsismo/ubuntu-16.04-samba:v0.3
    container_name: ubuntu-16.04-samba
    hostname: ubuntu-1604-samba 
    environment:
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /opt/docker/ubuntu-16.04-samba/shares-config:/etc/samba/smb.conf.d 
      - /opt/docker/ubuntu-16.04-samba/config/global-tunning.conf:/etc/samba/global-tunning.conf   #optional
      - /var/sambashare:/var/sambashare 
    ports:
      - 139:139
      - 445:445
    restart: unless-stopped
