# Despliega un compose.yml con un contenedor de pihole y otro de wireguard.
# Provee vpn y DNS con filtro de publicidad.
# Sincroniza un lan.list para tener dns interno.
---
- hosts: rbpi5002.sismonda.local
  become: yes

  tasks:
  - name: Include Docker Task
    ansible.builtin.include_tasks: "../modules/docker.yml"

  - name: Include NFS Task
    ansible.builtin.include_tasks: "../modules/nfs.yml"

  - name: Crear directorio /opt/utils
    file:
      path: /opt/utils
      state: directory

  - name: Crear directorio /mnt/storage
    file:
      path: /mnt/storage
      state: directory

  - name: Crear directorio /var/docker-data/ext-www
    file:
      path: /var/docker-data/ext-www
      state: directory

  - name: Crear directorio /var/docker-data/ext-www/mysql
    file:
      path: /var/docker-data/ext-www/mysql
      state: directory

  - name: Crear directorio /var/docker-data/ext-www/nextcloud
    file:
      path: /var/docker-data/ext-www/nextcloud
      state: directory

  - name: Crear directorio /var/docker-data/ext-www/nextcloud-redis
    file:
      path: /var/docker-data/ext-www/nextcloud-redis
      state: directory

  - name: Crear directorio /var/docker-data/ext-www/npm
    file:
      path: /var/docker-data/ext-www/npm
      state: directory

  - name: Crear directorio /var/docker-data/ext-www/wordpress
    file:
      path: /var/docker-data/ext-www/wordpress
      state: directory

  - name: Crear directorio /var/docker-data/ext-www/wordpress-redis
    file:
      path: /var/docker-data/ext-www/wordpress-redis
      state: directory

  - name: Crear directorio /opt/docker/ext-www
    file:
      path: /opt/docker/ext-www
      state: directory

  - name: Copy Nextcloud site config and cron files
    ansible.builtin.copy:
      src: /mnt/storage/ansible/ubu2404/ext-www/opt/docker/ext-www/nextcloud/
      dest: /opt/docker/ext-www/nextcloud/

  - name: Copy sql create database files
    ansible.builtin.copy:
      src: /mnt/storage/ansible/ubu2404/ext-www/opt/docker/ext-www/sql/
      dest: /opt/docker/ext-www/sql/

  - name: Copiar compose.yml
    template:
      src: /mnt/storage/ansible/ubu2404/ext-www/opt/docker/ext-www/docker-compose.yml
      dest: /opt/docker/ext-www/docker-compose.yml
      owner: root
      group: root
      mode: 0640
      backup: yes

  - name: Copiar do.sh
    template:
      src: /mnt/storage/ansible/ubu2404/ext-www/opt/docker/ext-www/do.sh
      dest: /opt/docker/ext-www/do.sh
      owner: root
      group: root
      mode: 0750
      backup: yes


  - name: Copiar compose .env
    template:
      src: /mnt/storage/ansible/ubu2404/ext-www/opt/docker/ext-www/.env
      dest: /opt/docker/ext-www/.env
      owner: root
      group: root
      mode: 0640
      backup: yes

  - name: Copiar nextcloud.txt
    template:
      src: /mnt/storage/ansible/ubu2404/ext-www/opt/docker/ext-www/nextcloud.txt
      dest: /opt/docker/ext-www/nextcloud.txt
      owner: root
      group: root
      mode: 0640
      backup: yes

  - name: Copiar ext-www.service
    template:
      src: /mnt/storage/ansible/ubu2404/ext-www/etc/systemd/system/ext-www.service
      dest: /etc/systemd/system/ext-www.service
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: Configurar ejecución de ext-www.service.
    systemd:
      name: ext-www.service
      state: started
      daemon_reload: yes
      enabled: yes


