# Despliega un compose.yml con un contenedor de pihole y otro de wireguard.
# Provee vpn y DNS con filtro de publicidad.
# Sincroniza un lan.list para tener dns interno.
---
- hosts: rbpi5002 
  become: yes

  tasks:
  - name: Include Docker Task
    ansible.builtin.include_tasks: "../modules/docker.yml"

  - name: Instalar nfs-common y rysnc.
    package:
      name:
       - nfs-common
       - rsync

  - name: Crear directorio /opt/utils
    file:
      path: /opt/utils
      state: directory

  - name: Crear directorio /mnt/storage
    file:
      path: /mnt/storage
      state: directory

  - name: Crear directorio /var/docker-data/ext-www
    file:
      path: /var/docker-data/ext-www
      state: directory

  - name: Crear directorio /var/docker-data/ext-www/mysql
    file:
      path: /var/docker-data/ext-www/mysql
      state: directory

  - name: Crear directorio /var/docker-data/ext-www/nextcloud
    file:
      path: /var/docker-data/ext-www/nextcloud
      state: directory

  - name: Crear directorio /var/docker-data/ext-www/nextcloud-redis
    file:
      path: /var/docker-data/ext-www/nextcloud-redis
      state: directory

  - name: Crear directorio /var/docker-data/ext-www/npm
    file:
      path: /var/docker-data/ext-www/npm
      state: directory

  - name: Crear directorio /var/docker-data/ext-www/wordpress
    file:
      path: /var/docker-data/ext-www/wordpress
      state: directory

  - name: Crear directorio /var/docker-data/ext-www/wordpress-redis
    file:
      path: /var/docker-data/ext-www/wordpress-redis
      state: directory

  - name: Crear directorio /opt/utils
    file:
      path: /opt/utils
      state: directory

  - name: Mount up device by label
    mount:
      path: /mnt/storage
      src: 10.0.0.9:/storage
      fstype: nfs
      opts: rw,soft,x-systemd.automount,rsize=131072,wsize=131072
      state: mounted

  - name: Copiar compose.yml
    template:
      src: /mnt/storage/ansible/ubu2404/ext-www/opt/docker/ext-www/docker-compose.yml
      dest: /opt/docker/ext-www/docker-compose.yml
      owner: root
      group: root
      mode: 0640
      backup: yes

  - name: Copiar phwrgrd.service
    template:
      src: /mnt/storage/ansible/ubu2404/phwrgrd/etc/systemd/system/ext-service.service
      dest: /etc/systemd/system/ext-service.service
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: Configurar ejecución de ext-www.service.
    systemd:
      name: ext-www.service
      state: started
      daemon_reload: yes
      enabled: yes

      
