---
version: "2.1"
services:

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - 8191:8191
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./radarr/config:/config
      - /mnt/storage/Plex/Videos/Movies:/movies #optional
      - /mnt/storage/Downloads/transmission:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./sonarr/config:/config
      - /mnt/storage/Plex/Videos/TV Shows:/tv #optional
      - /mnt/storage/Downloads/transmission:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:arm64v8-latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
        #      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=transmission #optional
      - PASS=S3cr3t0 #optional
#      - WHITELIST=iplist #optional
#      - HOST_WHITELIST=dnsnane list #optional
    volumes:
      - ./transmission/config:/config
      - /mnt/storage/Downloads/transmission:/downloads
      - /mnt/storage/Downloads/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
