---
- hosts: all:!rbpi3-001.sismonda.local 
  become: yes 

  tasks:
  - name: Instalar Chrony.
    package:
      name: 
       - chrony
      state: latest

  - name: Copiar chrony.conf.
    template:
      src: /etc/ansible/utils/chrony/chrony.conf 
      dest: /etc/chrony/chrony.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: Verificar ejecución de Chrony.
    systemd: 
      name: chrony
      state: started
      daemon_reload: yes
      enabled: yes
