---
- hosts: all:!rbpi4-002.sismonda.local 
  become: yes 

  tasks:
  - name: Instalar Nut.
    package:
      name: 
       - nut 
      state: latest

  - name: Copiar nut.conf.
    template:
      src: /etc/ansible/utils/nut/nut.conf 
      dest: /etc/nut/nut.conf
      owner: root
      group: nut
      mode: 0640
      backup: yes

  - name: Copiar upsmon.conf.
    template:
      src: /etc/ansible/utils/nut/upsmon.conf 
      dest: /etc/nut/upsmon.conf
      owner: root
      group: nut
      mode: 0640

  - name: Copiar upssched.conf.
    template:
      src: /etc/ansible/utils/nut/upssched.conf 
      dest: /etc/nut/upssched.conf
      owner: root
      group: nut
      mode: 0640

  - name: Verificar ejecución de Nut.
    systemd: 
      name: nut-client 
      state: started
      daemon_reload: yes
      enabled: yes
