---
- hosts: rbpi4004.sismonda.local 
  become: yes

  tasks:
  - name: Include Nerdctl Task
    ansible.builtin.include_tasks: "../modules/nerdctl.yml"

  - name: Crear directorio /opt/containerd/npm
    file:
      path: /opt/containerd/npm
      state: directory

  - name: Copiar Compose
    template:
      src: /etc/ansible/containerd/npm/opt/containerd/npm/compose.yml
      dest: /opt/containerd/npm/compose.yml
      owner: root
      group: root
      mode: 0640
      backup: yes

  - name: Copiar npm.service
    template:
      src: /etc/ansible/containerd/npm/etc/systemd/system/npm.service
      dest: /etc/systemd/system/npm.service
      owner: root
      group: root
      mode: 0755
      backup: yes
      
  - name: Configurar ejecución de npm.service.
    systemd:
      name: npm.service
      state: started
      daemon_reload: yes
      enabled: yes
